#!/bin/csh

rm -rf html/-ANR -ANR-big-main.*
rm -rf html/-CLEI -CLEI-big-main.*
rm -rf html/-SBC -SBC-big-main.*
rm -rf html/IS-SPC IS-SPC-big-main.*
rm -rf html/-UCR -UCR-big-main.*
rm -rf html/IS-UCSP IS-UCSP-big-main.*
rm -rf html/-UNAM -UNAM-big-main.*
rm -rf html/-UNMSM -UNMSM-big-main.*
rm -rf html/IS-UNSA IS-UNSA-big-main.*
rm -rf html/-USGP -USGP-big-main.*
rm -rf html/IS-UTEC IS-UTEC-big-main.*

./scripts/updatelog.pl "ANR: Starting compilation ..."
./compile  -ANR 
./gen-html -ANR

./scripts/updatelog.pl "CLEI: Starting compilation ..."
./compile  -CLEI 
./gen-html -CLEI

./scripts/updatelog.pl "SBC: Starting compilation ..."
./compile  -SBC 
./gen-html -SBC

./scripts/updatelog.pl "SPC: Starting compilation ..."
./compile  IS-SPC 
./gen-html IS-SPC

./scripts/updatelog.pl "UCR: Starting compilation ..."
./compile  -UCR 
./gen-html -UCR

./scripts/updatelog.pl "UCSP: Starting compilation ..."
./compile  IS-UCSP 
./gen-html IS-UCSP

./scripts/updatelog.pl "UNAM: Starting compilation ..."
./compile  -UNAM 
./gen-html -UNAM

./scripts/updatelog.pl "UNMSM: Starting compilation ..."
./compile  -UNMSM 
./gen-html -UNMSM

./scripts/updatelog.pl "UNSA: Starting compilation ..."
./compile  IS-UNSA 
./gen-html IS-UNSA

./scripts/updatelog.pl "USGP: Starting compilation ..."
./compile  -USGP 
./gen-html -USGP

./scripts/updatelog.pl "UTEC: Starting compilation ..."
./compile  IS-UTEC 
./gen-html IS-UTEC

